import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Molecules/Navbar'
import { GlobalState } from '@/components/Atoms/ContextoQuizz'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <GlobalState>
        {children}
        </GlobalState>   
        </body>
    </html>
  )
}
